//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vanzari
    {
        public int Id { get; set; }
        public Nullable<int> ProdusID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> AngajatID { get; set; }
    }
}
