//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace city_roads
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drum
    {
        public int Id { get; set; }
        public Nullable<int> From { get; set; }
        public Nullable<int> to { get; set; }
    }
}
